export const PROCESSING_STATUS = {
    PENDING: "PENDING",
    UPLOADED: "UPLOADED",
    PROCESSING: "PROCESSING",
    COMPLETED: "COMPLETED",
    ERROR: "ERROR"
};

export const UPSTREAM_STATUS = {
    PENDING: "PENDING",
    PROCESSING: "PROCESSING",
    SUCCESS: "SUCCESS",
    FAILURE: "FAILURE"
};

export const DOCUMENTS_STATUS = {
    PENDING: "PENDING",
    NOTFOUND: "NOTFOUND",
    COMPLETED: "COMPLETED"
};
