#!/usr/bin/env bash
#
# One-time setup of the Dev Space voice backend on the ccoex VPS.
#
# Clones feature-voiceRAG into a FRESH tree, builds two venvs, downloads
# the four sherpa-onnx voice bundles and a static ffmpeg, and writes both
# .env files. Idempotent: safe to re-run.
#
# ─────────────────────────────────────────────────────────────────────
# Why a fresh clone and not an existing checkout:
#   ~/Desktop/intramind_staging/... is the LIVE tree serving real traffic,
#   and its AI checkout has uncommitted work — a `git checkout` there
#   loses it. ~/intramind-build is the frozen packaging tree. Cloning
#   costs two minutes and removes the whole class of mistake.
#
# Why no sudo and no apt:
#   `ccoex` has no passwordless sudo, so /opt is unreachable — hence the
#   home-dir model dirs. And a past apt run on this box upgraded the
#   NVIDIA userspace driver mid-flight and killed every new GPU
#   container, so ffmpeg comes from a static tarball.
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT="${DEVSPACE_ROOT:-$HOME/devspace}"
GH="${GH_BASE:-https://github.com/pnv7337}"
AI_COMMIT="${AI_COMMIT:-985698a}"
SERVING_COMMIT="${SERVING_COMMIT:-9f93248}"
UV="${UV:-$HOME/.local/bin/uv}"

log() { printf '\n\033[1m▸ %s\033[0m\n' "$*"; }
die() { printf '\033[31m✗ %s\033[0m\n' "$*" >&2; exit 1; }

[ -x "$UV" ] || die "uv not found at $UV"

log "creating $ROOT"
mkdir -p "$ROOT"/{models/tts,models/stt,bin,logs,ops}
cd "$ROOT"

# ── Clone ────────────────────────────────────────────────────────────
for repo in mta-ai-intramind mta-ai-serving-intramind; do
  if [ -d "$repo/.git" ]; then
    log "$repo already cloned"
  else
    log "cloning $repo @ feature-voiceRAG"
    git clone -q -b feature-voiceRAG "$GH/$repo.git"
  fi
done

# Pin: the E2E that proved this feature ran on these exact commits, and
# one of them (9425492) IS the fix for the WEDGED race that E2E found.
git -C mta-ai-intramind rev-parse HEAD | grep -q "^$AI_COMMIT" \
  || die "mta-ai-intramind is not at $AI_COMMIT"
git -C mta-ai-serving-intramind rev-parse HEAD | grep -q "^$SERVING_COMMIT" \
  || die "mta-ai-serving-intramind is not at $SERVING_COMMIT"

# ── Venvs ────────────────────────────────────────────────────────────
for repo in mta-ai-serving-intramind mta-ai-intramind; do
  if [ -x "$repo/.venv/bin/python" ]; then
    log "$repo venv exists"
  else
    log "building $repo venv"
    (cd "$repo" && "$UV" venv .venv --python 3.12 \
      && "$UV" pip install --python .venv/bin/python -r requirements.txt)
  fi
done

# ── Static ffmpeg ────────────────────────────────────────────────────
# Two consumers: STT decoding anything that is not WAV, and the episode
# stitcher's mp3 encode. Both degrade rather than crash without it (STT
# 503s on non-WAV; episodes ship as ~10x larger wav), and the FE encodes
# WAV in the browser precisely so the STT path never needs this.
if [ -x "$ROOT/bin/ffmpeg" ]; then
  log "ffmpeg already present"
else
  log "installing static ffmpeg (NOT apt — see header)"
  tmp=$(mktemp -d)
  curl -fsSL -o "$tmp/ffmpeg.tar.xz" \
    https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
  tar xf "$tmp/ffmpeg.tar.xz" -C "$tmp"
  cp "$tmp"/ffmpeg-*-amd64-static/{ffmpeg,ffprobe} "$ROOT/bin/"
  rm -rf "$tmp"
  "$ROOT/bin/ffmpeg" -version | head -1
fi

# ── Voice models ─────────────────────────────────────────────────────
log "downloading voice model bundles"
# HF_HOME giữ ở cache mặc định của máy, KHÔNG tách riêng: embedder Harrier của
# chính tiến trình này chạy với HF_HUB_OFFLINE=1 và tìm trong cache mặc định —
# trỏ HF_HOME đi chỗ khác là serving chết ngay lúc nạp embedder.
TTS_MODELS_DIR="$ROOT/models/tts" STT_MODELS_DIR="$ROOT/models/stt" \
  HF_HOME="${HF_HOME:-$HOME/.cache/huggingface}" \
  bash mta-ai-serving-intramind/docker/voice_model_download.sh
du -sh "$ROOT/models/tts" "$ROOT/models/stt"

# ── serving .env ─────────────────────────────────────────────────────
log "writing serving .env"
cat > mta-ai-serving-intramind/.env <<EOF
# Dev Space voice serving. Generated by devspace-bootstrap.sh.

# The embedder loads unconditionally (app/main.py set_embedder is not
# wrapped in try/except), so it cannot be switched off — only moved off
# the GPU. ~1 GB RAM, 0 VRAM.
EMBEDDING_DEVICE=cpu
HF_HUB_OFFLINE=1
TRANSFORMERS_OFFLINE=1

# LOAD-BEARING. The card has ~3.7 GB free. A second jina-v3 (~2 GB plus a
# ~1.8 GB listwise spike) would OOM the LIVE answer LLM. The dev AI
# reranks via the live :5003 instead.
ENABLE_RERANKER=false

# Chỉ tiếng Việt, BỐN giọng: 2 Piper (đường lùi) + 2 VieNeu (chất lượng cao).
#   vi_female    = vais1000-medium (1 speaker, 22050 Hz)
#   vi_male      = vivos-x_low     (65 speaker, 16000 Hz) — sid chọn bằng audition F0
#   vi_*_hq      = VieNeu-TTS v3 Turbo (48 kHz, ONNX CPU) — giọng mặc định của
#                  podcast từ 2026-08-18; trọng số nằm trong HF cache, không
#                  nằm trong TTS_MODEL_DIR.
ENABLE_TTS=true
TTS_VOICE_VI_FEMALE=piper_vi_female
TTS_VOICE_VI_MALE=piper_vi_male
TTS_VOICE_VI_MALE_SID=38
TTS_VOICE_VI_FEMALE_HQ=vieneu_vi_female
TTS_VOICE_VI_MALE_HQ=vieneu_vi_male
TTS_VIENEU_SPEAKER_FEMALE=Kim Thanh
TTS_VIENEU_SPEAKER_MALE=Minh Đức
TTS_VIENEU_PRECISION=int8
# 64 chứ không phải 256 mặc định: 256 tốn thêm ~2,5 GB RAM và CHẬM hơn.
TTS_VIENEU_MAX_CHARS=64
TTS_VIENEU_MAX_BATCH=1
TTS_VIENEU_IDLE_TIMEOUT=600
# 48000 = tần số gốc của VieNeu. Bộ resample không có lọc chống răng cưa nên
# không bao giờ đặt thấp hơn tần số gốc của engine đang nạp.
TTS_OUTPUT_SAMPLE_RATE=48000
TTS_MODEL_DIR=$ROOT/models/tts
TTS_DEVICE=cpu
TTS_NUM_THREADS=2
TTS_MAX_TEXT_CHARS=2000

ENABLE_STT=true
STT_ENGINE_VI=sherpa_vi_30m
STT_MODEL_DIR=$ROOT/models/stt
# GPU không nhanh hơn CPU với model int8 nhỏ (đo thật trên 4090) — để cpu.
STT_DEVICE=cpu
STT_NUM_THREADS=2
STT_MAX_AUDIO_BYTES=26214400
EOF

# ── AI .env ──────────────────────────────────────────────────────────
# Seeded from the LIVE .env so LLM URLs, keys and model aliases match
# this box (it runs gemma on :5011, not the alias in .env_example).
LIVE_AI_ENV="$HOME/Desktop/intramind_staging/mta-intramind/mta-ai-intramind/.env"
if [ -f "mta-ai-intramind/.env" ]; then
  log "AI .env already exists — leaving it alone"
else
  [ -f "$LIVE_AI_ENV" ] || die "cannot read live .env at $LIVE_AI_ENV"
  log "writing AI .env (seeded from live, then overridden)"
  # Read-only copy. The live file is never modified.
  cp "$LIVE_AI_ENV" mta-ai-intramind/.env
  cat >> mta-ai-intramind/.env <<EOF

# ── Dev Space overrides (appended; later keys win) ──────────────────
PORT=15001

# Retrieval reads stay on the SHARED datastores — that is what "read the
# real corpus" means. The AI tier has no index-write path.
EMBEDDING_BASE_URL=http://localhost:5003
RERANKER_BASE_URL=http://localhost:5003
INGESTION_BASE_URL=http://localhost:5002

# Dedicated Redis. NOT a preference: the live Celery app has the same
# name (intramind_worker) on the same broker db, and the worker's default
# queue list overlaps live's five queues — sharing the broker means this
# worker eats real users' summaries and reports.
# No /N suffix: celery_app.py appends /0 and /1 itself.
REDIS_URL=redis://localhost:16379
CACHE__REDIS_DB=2

ENABLE_AUDIO_OVERVIEW=true
ENABLE_STT=true
TTS_BASE_URL=http://localhost:15003
STT_BASE_URL=http://localhost:15003
# 420, không phải 120: VieNeu chạy CPU ở RTF ~1,6x nên một lượt thoại 3 phút
# mất ~110s, lượt đầu cộng thêm ~12s nạp model. 120s là ngưỡng của thời Piper.
TTS_TIMEOUT_SECONDS=420
STT_TIMEOUT_SECONDS=120
STT_MAX_UPLOAD_SIZE=26214400

# 2, không phải 4: engine HQ là model tự hồi quy chạy CPU trên máy dùng chung.
AUDIO_OVERVIEW_TTS_BATCH_SIZE=2
AUDIO_OVERVIEW_WPM=150
# 3, not the service default of 10: a demo should finish while the person
# who started it is still watching.
AUDIO_OVERVIEW_TARGET_MINUTES=3
AUDIO_OVERVIEW_MAX_MINUTES=30

MINIO_ENDPOINT=localhost:19000
MINIO_ACCESS_KEY=devspace
MINIO_SECRET_KEY=devspace123
MINIO_BUCKET=audio-overviews-devspace
MINIO_SECURE=false

ENABLE_KNOWLEDGE_GRAPH=false
TRACING__ENABLED=false
EOF
fi

log "bootstrap done — next: ops/devspace-up.sh"
